# Generated by Django 5.2.7 on 2025-10-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
